{% set name = "dtool_cli" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-cli/dtool-cli-{{ version }}.tar.gz
  sha256: 2664750dd76ece7d41e8aa7288cda66aef2f04eb4d39dcd13484fc1a193d3385

build:
  number: 0
  noarch: python
  entry_points:
    - dtool = dtool_cli.cli:dtool
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - click-plugins
    - setuptools
    - dtoolcore

test:
  commands:
    - dtool --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool-cli
  license: MIT
  license_file: LICENSE.rst
  summary: The dtool-cli python package provides a skeleton command line interface to dtool that other "dtool" command line packages can be plugged into.
  doc_url: https://github.com/jic-dtool/dtool-cli
  dev_url: https://github.com/jic-dtool/dtool-cli

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
