{% set name = "dtool_cli" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-cli/dtool-cli-{{ version }}.tar.gz
  sha256: "0e320ad42766485c931ab0338e36f0e498839522761684dc95ed347f261185c2"

build:
  number: 3
  noarch: python
  entry_points:
    - dtool = dtool_cli.cli:dtool
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - click-plugins
    - setuptools
    - dtoolcore

test:
  commands:
    - dtool --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool-cli
  license: MIT
  license_file: LICENSE.rst
  summary: 'The dtool-cli python package provides a skeleton command line interface to dtool that other "dtool" command line packages can be plugged into.'
  doc_url: https://github.com/jic-dtool/dtool-cli
  dev_url: https://github.com/jic-dtool/dtool-cli

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
