travis:
  secure:
    BINSTAR_TOKEN: Det7KoczmK1La3FSWFT9LkPg6gy4I3v+fy8EaH+0zEtkyZmZtjzHTwgnvXWYtpZavRRiledm2KznYV7lhsmFOwusd32zLWGQswYEtqmFw4A5zE6++cbNJDKb4M2yOBO0jCkrYpcesXJ5OtVovRtY4TodHe75WPNLJeczs5pHt4rzTNdf2Q7+znGovY5ift0gB95Wp/CWwqGoWppFrTfoeqN26nXfffOuVWgbiMbSOlm8nXq/CeyJM2FCgTxOdf5fTrTh9fxLDobGcPy+8RDrFsIoNJ0Guu3bHFF7kVeTb+SIVDWzrZ3C7pcmjI86gHTQVI3G1+04CI044UYhcfdbnZFHIEKnlw0mYlMk44XE/0I0V7WERNgJbxjSXG1rWalNCtTz3nYb1eVj6cSsKGmD0NLRRItcNvsW93lBho1TXwhFKy3tfuFiLBq7s9hYr/tDeNGgKjUdt4q9lvG6qyG/lcWZG0pagviXLilhu+Y6jtMJDN+l8V8fLldpEojVBpPhpt6bsJHasxs85XaS5w+uOb5uZGIAiGtzQx38gMj7NeeuUH7EK/sujIAsOn9i5M+/i0YyDLWquEXpvTIeEpqK7THeV7cZMSOh/s4C7SM8riUNhMPdKhS+yR+uMSVi9KW3g4eeZoJjb76ZmE6aLpFU/nm5V1mMQ1oB9RBx605Kr00=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
